### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bboydflo** [dlzi/brevis#1]
Hey! Brevis looks great, but what is different from Tachyons? It seems they have a lot in common.

**Comment by dlzi** [comment]
Good question!

We all(Brevis, Tachyons, Tailwind and Basscss) share the same philosophy. An utility-first (https://getbrevis.com/faq.html#naming-the-approach) CSS toolkit.

Under the hood, Brevis(IMHO) has a more logical and easier naming convention, a very consistent numerical scale and an improved specificity control. There are also differences in the way we handle responsiveness. For more details take a look at https://getbrevis.com/faq.html#why-brevis.

**Comment by bboydflo** [comment]
Thanks for the answer. Will close this now :) 👍
